spring.application.name=supershop

spring.datasource.url=jdbc:postgresql://dpg-d7900t6a2pns73drlgqg-a.singapore-postgres.render.com/supershop
spring.datasource.username=weldon
spring.datasource.password=VEY85S2ZJs6fEThbu62DDYpuFI1PBFID

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080